# Generated by Django 3.2.7 on 2021-10-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('mentor', models.CharField(max_length=100)),
                ('mentee', models.CharField(max_length=100)),
                ('reporting_month', models.IntegerField()),
                ('mentee_engagement', models.IntegerField()),
                ('mentee_on_time', models.IntegerField()),
            ],
        ),
    ]
