# Generated by Django 3.2.11 on 2022-05-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('isAnnual', models.BooleanField()),
            ],
        ),
    ]
