# Generated by Django 3.2.11 on 2022-05-28 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Holidays',
            new_name='Holiday',
        ),
    ]
