# Generated by Django 3.2.11 on 2022-06-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_rename_holidays_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='note',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
