# Used for running the server in a local development environment.
# Automatically overrides values in base `docker-compose.yml` file when
# exeucting a `docker compose up`
version: "3.9"
services:
  views-mock:
    command: sh -c "python manage.py createdb && python manage.py runserver 0.0.0.0:5001"
    volumes:
      - ./views_mock:/code
    ports:
      - "5001:5001"
  server:
    command: sh -c "python -m unittest baytree_app/testing/FluentLoggerTests.py && python manage.py runserver 0.0.0.0:8000 || python baytree_app/testing/test_failure_log.py"
    ports:
      - "8000:8000"
    volumes:
      - ./baytree_app:/code
    environment:
      - DEBUG=yes
  database:
    ports:
      - "3306:3306"
  frontend:
    container_name: baytree_frontend
    image: node:16
    command: npm start
    working_dir: /code
    volumes:
      - ./frontend:/code
    ports:
      - "3000:3000"
  admin-frontend:
    container_name: baytree_admin_frontend
    image: node:14
    command: npm run dev
    working_dir: /code
    volumes:
      - ./admin-frontend:/code
    ports:
      - "3001:3001"