version: "3.9"
services:
  mock-views-app:
    container_name: mock-views-app
    build:
      context: ./mock-views-app
  server:
    container_name: baytree_server
    build:
      context: ./baytree_app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MYSQL_HOST=baytree_database
      - MYSQL_DATABASE=baytree
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - VIEWS_USERNAME=${VIEWS_USERNAME}
      - VIEWS_PASSWORD=${VIEWS_PASSWORD}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - LOGGING_URL=${LOGGING_URL}

    depends_on:
      - database
      - redis
      - fluent-bit
  database:
    container_name: baytree_database
    image: mariadb:10.9.4
    environment:
      - MYSQL_DATABASE=baytree
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - baytree_database_data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:latest

  fluent-bit:
    image: fluent/fluent-bit
    container_name: fluentbit
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./fluent-bit/testLog/:/fluent-bit/etc/testLog/
      - ./baytree_app/server_logs/:/baytree_app/etc/server_logs
    ports:
      - "24224:24224/tcp"
      - "24224:24224/udp"
      - "24223:24223/tcp"
      - "24223:24223/udp"
    environment:
      AWS_ACCESS_KEY_ID : ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY : ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION : ${AWS_DEFAULT_REGION}
      GRAFANA_LOGGING_URL: ${GRAFANA_LOGGING_URL}
      GRAFANA_USER: ${GRAFANA_USER}
      GRAFANA_API_KEY: ${GRAFANA_API_KEY}

volumes:
  baytree_database_data: