# Used for deployment to a server where we are getting images from Docker Hub
# Overlay ontop of base config with:
#    $ export IMAGE_TEST="latest"
#    $ docker compose -f docker-compose.yml -f docker-compose.deploy.yml up -d
# Set IMAGE_TAG to the image desired, such as:
#     latest
#     dev
#     staging
#     vYYYY-MM-DD.SHA
version: "3.9"
services:
  server:
    image: drbfraser/baytree_mentor-support-tool_backend:$IMAGE_TAG
    restart: always
    command: gunicorn baytree_app.wsgi --bind 0:8000
    environment:
      - DOMAIN=${DOMAIN}
  database:
    restart: always
  caddy:
    container_name: baytree_revproxy_frontend
    image: drbfraser/baytree_mentor-support-tool_revproxy_frontend:$IMAGE_TAG
    build:
      context: .
      dockerfile: caddy/Dockerfile
    restart: always
    environment:
      - DOMAIN=${DOMAIN}
      - API_HOSTNAME=baytree_server
    ports:
      - "80:80"
      - "443:443"