version: "3.9"
services:
  server:
    container_name: baytree_server
    build:
      context: ./baytree_app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MYSQL_HOST=baytree_database
      - MYSQL_DATABASE=baytree
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - VIEWS_USERNAME=${VIEWS_USERNAME}
      - VIEWS_PASSWORD=${VIEWS_PASSWORD}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}

    depends_on:
      - database
      - redis
      - fluent-bit
  database: 
    container_name: baytree_database
    image: mariadb:5.5
    environment:
      - MYSQL_DATABASE=baytree
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - baytree_database_data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:latest

  fluent-bit:
    image: fluent/fluent-bit
    container_name: fluentbit
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
    ports:
      - "24224:24224/tcp"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.6.2
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

volumes:
  baytree_database_data: