version: "3.9"
services:
  server:
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./baytree_app:/code
    environment:
      - DEBUG=yes
  database:
    ports:
      - "3306:3306"