version: "3.9"
services:
  views-mock:
    container_name: views-mock
    build:
      context: ./
      dockerfile: ./views_mock/Dockerfile
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MYSQL_HOST=baytree_database
      - MYSQL_DATABASE=baytree
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - VIEWS_MYSQL_DATABASE=${VIEWS_MYSQL_DATABASE}
      - VIEWS_MYSQL_HOST=${VIEWS_MYSQL_HOST}
    depends_on:
      - views-mock-db
      - database
      - redis
      - fluent-bit
  server:
    container_name: baytree_server
    build:
      context: ./
      dockerfile: ./baytree_app/Dockerfile
    environment:
      SECRET_KEY: ${SECRET_KEY}
      MYSQL_HOST: baytree_database
      MYSQL_DATABASE: baytree
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      VIEWS_USERNAME: ${VIEWS_USERNAME}
      VIEWS_PASSWORD: ${VIEWS_PASSWORD}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      VIEWS_BASE_URL: ${VIEWS_BASE_URL:-http://views-mock:5001/}

    depends_on:
      - views-mock-db
      - database
      - redis
      - fluent-bit
  database:
    container_name: baytree_database
    image: mariadb:10.9.4
    environment:
      MYSQL_DATABASE: baytree
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - baytree_database_data:/var/lib/mysql
  views-mock-db:
    container_name: views-mock-db
    image: mariadb:10.9.4
    environment:
      - MYSQL_DATABASE=baytree
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - VIEWS_MYSQL_DATABASE=${VIEWS_MYSQL_DATABASE}
      - VIEWS_MYSQL_HOST=${VIEWS_MYSQL_HOST}
    volumes:
      - views-mock-data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:latest

  fluent-bit:
    image: fluent/fluent-bit
    container_name: fluentbit
    volumes:
      # Dynamically mounts correct conf file based on current environment
      - ./fluent-bit/fluent-bit-${ENVIRONMENT:-local}.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - ./fluent-bit/testLog/:/fluent-bit/etc/testLog/
      - ./fluent-bit/inputs/:/fluent-bit/etc/inputs/
      - ./fluent-bit/outputs/:/fluent-bit/etc/outputs/
      - ./fluent-bit/filters/:/fluent-bit/etc/filters/
      - ./baytree_app/server_logs/:/baytree_app/etc/server_logs
    ports:
      - "24224:24224/tcp"
      - "24224:24224/udp"
      - "24223:24223/tcp"
      - "24223:24223/udp"
    environment:
      # Used in production and staging
      AWS_ACCESS_KEY_ID : ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY : ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION : ${AWS_DEFAULT_REGION}

      # Used in dev
      GRAFANA_LOGGING_URL: ${GRAFANA_LOGGING_URL}
      GRAFANA_USER: ${GRAFANA_USER}
      GRAFANA_API_KEY: ${GRAFANA_API_KEY}

      ENVIRONMENT: ${ENVIRONMENT}

volumes:
  baytree_database_data:
  views-mock-data: