version: '2.3'

services:
    log_creator:
        image: alpine:3.12.4
        container_name: log_creator
        command: >
            sh -c '
                counter=0
                while :
                do
                    sleep 1
                    echo "{\"message\": \"log line $$counter\", \"something\": \"else\"}"
                    counter=$$(($$counter + 1))
                done'
        environment:
            SERVICE_NAME: log_creator
        logging:
            driver: fluentd
            options:
                env: SERVICE_NAME