FROM caddy:2.4.6

# these paths are relative to the project root, not this folder
ADD caddy/Caddyfile /etc/caddy/Caddyfile
ADD frontend_build.tar.gz /var/www/frontend
ADD admin_frontend_build.tar.gz /var/www/admin-frontend
