# Generated by Django 3.2.11 on 2022-02-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoruser',
            name='viewsId',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
