# Generated by Django 3.2.11 on 2022-02-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_mentoruser_viewsid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentoruser',
            old_name='viewsId',
            new_name='viewsPersonId',
        ),
        migrations.AlterField(
            model_name='mentoruser',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Withdrawn', 'Withdrawn'), ('On Hold', 'On Hold'), ('Temporarily Withdrawn', 'Temporarily Withdrawn'), ('Future Leaver', 'Future Leaver'), ('Staff', 'Staff'), ('Inactive', 'Inactive')], default='Active', max_length=30),
        ),
    ]
