# Generated by Django 3.2.11 on 2022-02-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20220215_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteeuser',
            name='mentorUsers',
            field=models.ManyToManyField(through='users.Mentoring', to='users.MentorUser'),
        ),
    ]
