# Generated by Django 3.2.11 on 2022-03-20 04:45

from django.db import migrations, models
import users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_menteeuser_mentorusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCreationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('account_type', models.CharField(choices=[('Mentor', 'Mentor'), ('Mentee', 'Mentee'), ('Admin', 'Admin')], default='Mentor', max_length=30)),
                ('views_person_id', models.CharField(default=None, max_length=30)),
                ('link_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date', models.DateTimeField(blank=True, default=users.models.generateAccountCreationLinkExpiryDateTime)),
            ],
        ),
    ]
