# Generated by Django 3.2.11 on 2022-05-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_mentorrole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentorrole",
            name="viewsSessionGroupId",
            field=models.IntegerField(null=True),
        ),
    ]
