# Generated by Django 3.2.11 on 2022-05-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_customuser_dataprivacyconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='data_privacy_consent',
            field=models.DateField(default=None),
        ),
    ]
