# Generated by Django 3.2.11 on 2022-06-04 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20220602_1945'),
        ('users', '0030_mentorrole_volunteeringtype'),
    ]

    operations = [
    ]
