# Generated by Django 3.2.14 on 2022-08-21 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='json_value',
            new_name='value',
        ),
    ]
