# Generated by Django 4.1.3 on 2023-03-17 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('createdBy', models.CharField(max_length=50, verbose_name='CreatedBy')),
                ('updatedBy', models.CharField(max_length=50, verbose_name='UpdatedBy')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceID', models.IntegerField(verbose_name='SourceID')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('valueListID', models.IntegerField(verbose_name='valueListID')),
                ('inputType', models.CharField(max_length=50, verbose_name='inputType')),
                ('validation', models.CharField(max_length=100, verbose_name='validation')),
                ('category', models.CharField(max_length=50, verbose_name='category')),
                ('enabled', models.IntegerField(verbose_name='enabled')),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evidence.questionnaire', verbose_name='QuestionnaireID')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000, verbose_name='Answer')),
                ('entityType', models.CharField(max_length=100, verbose_name='EntityType')),
                ('entityID', models.IntegerField(verbose_name='EntityID')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('answerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerIdOfQuestion', to='evidence.question', verbose_name='AnswerID')),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionIdOfQuestion', to='evidence.question', verbose_name='QuestionID')),
            ],
        ),
    ]
