# Generated by Django 4.1.3 on 2023-03-19 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('QuestionnaireID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.CharField(max_length=50)),
                ('UpdatedBy', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('SourceID', models.IntegerField()),
                ('Question', models.CharField(max_length=500)),
                ('valueListID', models.IntegerField()),
                ('inputType', models.CharField(max_length=50)),
                ('validation', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('enabled', models.IntegerField()),
                ('QuestionnaireID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evidence.questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(max_length=1000)),
                ('EntityType', models.CharField(max_length=100)),
                ('EntityID', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('AnswerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answerIdOfQuestion', to='evidence.question')),
                ('QuestionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionIdOfQuestion', to='evidence.question')),
            ],
        ),
    ]
