# Generated by Django 4.1.3 on 2023-04-18 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_alter_answer_answersetid_alter_answer_questionid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerset',
            name='QuestionID',
        ),
        migrations.AddField(
            model_name='answerset',
            name='QuestionnaireID',
            field=models.ForeignKey(db_column='QuestionnaireID', default=9999999, on_delete=django.db.models.deletion.CASCADE, to='evidence.questionnaire'),
            preserve_default=False,
        ),
    ]
