# Generated by Django 4.1.3 on 2023-04-19 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_remove_answerset_questionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='QuestionnaireID',
            field=models.ForeignKey(db_column='QuestionnaireID', on_delete=django.db.models.deletion.CASCADE, to='evidence.questionnaire'),
        ),
    ]
