# Generated by Django 3.2.7 on 2021-11-29 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0007_remove_monthlyreport_question_and_answer_list'),
        ('questions_and_answers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionandanswer',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questionnaire'),
        ),
    ]
