# Generated by Django 3.2.7 on 2021-12-02 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0008_auto_20211202_0054'),
        ('questions_and_answers', '0002_questionandanswer_monthly_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionandanswer',
            name='questionnaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions_and_answers', to='questionnaires.questionnaire'),
        ),
    ]
