# Generated by Django 3.2.11 on 2022-06-03 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_and_answers', '0002_remove_questionandanswer_questionnaire'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionAndAnswer',
        ),
    ]
