# Generated by Django 3.2.7 on 2021-11-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('goal_review_date', models.DateField()),
                ('content', models.CharField(max_length=1000)),
                ('status', models.CharField(choices=[('ACHIEVED', 'ACHIEVED'), ('IN PROGRESS', 'IN PROGRESS'), ('RECALIBRATED', 'RECALIBRATED')], default='IN PROGRESS', max_length=12)),
            ],
        ),
    ]
