# Generated by Django 3.2.7 on 2021-11-23 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0002_rename_goals_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='details',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='user',
        ),
        migrations.AddField(
            model_name='goal',
            name='content',
            field=models.CharField(default='a', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_review_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='mentee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goal_mentee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goal_mentor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('ACHIEVED', 'ACHIEVED'), ('IN PROGRESS', 'IN PROGRESS'), ('RECALIBRATED', 'RECALIBRATED')], default='IN PROGRESS', max_length=12),
        ),
        migrations.AlterField(
            model_name='goal',
            name='title',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
