# Generated by Django 3.2.11 on 2022-03-02 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0004_alter_goal_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='mentee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_mentee', to=settings.AUTH_USER_MODEL),
        ),
    ]
