# Generated by Django 3.2.11 on 2022-06-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_goal_last_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='mentee',
        ),
        migrations.AddField(
            model_name='goal',
            name='mentee_id',
            field=models.IntegerField(null=True),
        ),
    ]
