# Generated by Django 3.2.11 on 2022-06-07 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_merge_20220604_1509'),
        ('goals', '0007_auto_20220606_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_mentor', to='users.mentoruser'),
        ),
    ]
