# Generated by Django 3.2.11 on 2022-07-13 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_alter_goal_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='mentee_id',
        ),
    ]
