# Generated by Django 3.2.11 on 2022-07-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_remove_goal_mentee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='options',
            field=models.ManyToManyField(to='goals.GoalOption'),
        ),
    ]
