# Generated by Django 3.2.7 on 2021-11-27 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_reports', '0002_auto_20211127_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyreport',
            name='question_and_response_list',
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='question_and_response_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monthly_reports.questionandresponse'),
        ),
    ]
