# Generated by Django 3.2.7 on 2021-11-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_and_answers', '0001_initial'),
        ('monthly_reports', '0005_auto_20211128_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyreport',
            name='question_and_answer_list',
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='question_and_answer_list',
            field=models.ManyToManyField(related_name='QAs_in_monthly_report', to='questions_and_answers.QuestionAndAnswer'),
        ),
    ]
