# Generated by Django 3.2.7 on 2021-11-29 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_reports', '0006_auto_20211129_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyreport',
            name='question_and_answer_list',
        ),
    ]
