# Generated by Django 4.1.3 on 2023-03-23 20:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('SessionID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('Updated', models.DateTimeField(null=True)),
                ('Name', models.CharField(max_length=255)),
                ('Activity', models.CharField(max_length=255, null=True)),
                ('LeadStaff', models.PositiveIntegerField()),
                ('Duration', models.CharField(max_length=255)),
                ('Cancelled', models.PositiveSmallIntegerField()),
                ('VenueID', models.PositiveIntegerField()),
                ('VenueName', models.CharField(max_length=255)),
                ('StartDate', models.DateField(default=django.utils.timezone.now)),
                ('StartTime', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SessionGroup',
            fields=[
                ('SessionGroupID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True)),
                ('LeadStaff', models.PositiveIntegerField(null=True)),
                ('OtherStaff', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attended', models.PositiveSmallIntegerField(null=True)),
                ('Role', models.CharField(max_length=255)),
                ('ReasonforNotAttending', models.TextField(blank=True)),
                ('Name', models.CharField(max_length=255)),
                ('ContactID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.person')),
                ('SessionID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='views_sessions.session')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='SessionGroupID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='views_sessions.sessiongroup'),
        ),
    ]
