# Generated by Django 4.1.3 on 2023-03-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('SessionID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('SessionGroupID', models.PositiveIntegerField()),
                ('Created', models.DateTimeField()),
                ('CreatedBy', models.CharField(default='', max_length=255)),
                ('Updated', models.DateTimeField()),
                ('UpdatedBy', models.CharField(default='', max_length=255)),
                ('RestrictedRecord', models.PositiveIntegerField()),
                ('SessionType', models.CharField(default='', max_length=255)),
                ('Name', models.CharField(default='', max_length=255)),
                ('Activity', models.CharField(default='', max_length=255)),
                ('LeadStaff', models.PositiveIntegerField()),
                ('ContactType', models.CharField(default='', max_length=255)),
                ('StartDate', models.DateField()),
                ('StartTime', models.TimeField()),
                ('Duration', models.CharField(default='', max_length=255)),
                ('Cancelled', models.PositiveSmallIntegerField()),
                ('VenueID', models.PositiveIntegerField()),
                ('VenueName', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
