# Generated by Django 4.1.3 on 2023-02-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_group_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField()),
                ('created_by', models.CharField(default='', max_length=255)),
                ('updated', models.DateTimeField()),
                ('updated_by', models.CharField(default='', max_length=255)),
                ('restricted_record', models.PositiveIntegerField()),
                ('session_type', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('activity', models.CharField(default='', max_length=255)),
                ('lead_staff', models.PositiveIntegerField()),
                ('contact_type', models.CharField(default='', max_length=255)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.CharField(default='', max_length=255)),
                ('cancelled', models.PositiveSmallIntegerField()),
                ('venue_id', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
