# Generated by Django 4.1.3 on 2023-03-24 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('views_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='SessionGroupID',
            field=models.ForeignKey(db_column='SessionGroupID', on_delete=django.db.models.deletion.CASCADE, to='views_sessions.sessiongroup'),
        ),
        migrations.AlterField(
            model_name='staffsession',
            name='SessionID',
            field=models.OneToOneField(db_column='SessionID', on_delete=django.db.models.deletion.CASCADE, to='views_sessions.session'),
        ),
    ]
