# Generated by Django 4.1.3 on 2023-04-07 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_delete_sessionnote'),
        ('views_sessions', '0002_alter_session_sessiongroupid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeID', models.ForeignKey(db_column='SessionID', on_delete=django.db.models.deletion.CASCADE, to='views_sessions.session')),
                ('note', models.OneToOneField(db_column='NoteID', on_delete=django.db.models.deletion.CASCADE, related_name='sessionNote', to='contacts.note')),
            ],
        ),
    ]
