# Generated by Django 3.2.7 on 2021-11-27 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentor_sessions', '0003_auto_20211123_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorsession',
            name='mentee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_mentee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentorsession',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_mentor', to=settings.AUTH_USER_MODEL),
        ),
    ]
