# Generated by Django 3.2.11 on 2022-04-15 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentor_sessions', '0005_delete_mentorsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attended_by_mentor', models.BooleanField(default=True)),
                ('attended_by_mentee', models.BooleanField(default=True)),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('cancelled', models.BooleanField(default=False)),
                ('viewsSessionId', models.CharField(max_length=50, null=True)),
                ('mentee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_mentee', to=settings.AUTH_USER_MODEL)),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_mentor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
