# Generated by Django 3.2.11 on 2022-05-30 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_mentorrole_activity'),
        ('mentor_sessions', '0008_merge_0006_mentorsession_0007_alter_activity_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
