# Generated by Django 3.2.11 on 2022-06-09 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_sessions', '0009_delete_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentorSession',
        ),
    ]
