# Generated by Django 3.2.11 on 2022-06-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_sessions', '0009_delete_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('viewsVenueId', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
