# Generated by Django 3.2.11 on 2022-06-28 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_sessions', '0010_delete_mentorsession'),
        ('mentor_sessions', '0010_venue'),
    ]

    operations = [
    ]
