# Generated by Django 4.1.3 on 2023-03-19 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValueList',
            fields=[
                ('ValueListID', models.IntegerField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ValueListItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
                ('valueList', models.OneToOneField(db_column='ValueListID', on_delete=django.db.models.deletion.CASCADE, related_name='ValueListItem', to='admin_valuelists.valuelist')),
            ],
        ),
    ]
