# Generated by Django 4.1.3 on 2023-03-19 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_valuelists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuelistitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='valuelistitem',
            name='valueList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_valuelists.valuelist'),
        ),
    ]
