# Generated by Django 4.1.3 on 2023-03-21 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_valuelists', '0002_alter_valuelistitem_id_alter_valuelistitem_valuelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuelist',
            name='Type',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Volunteer', 'Volunteer'), ('Individual', 'Individual'), ('Person', 'Person'), ('Group', 'Group'), ('Session', 'Session'), ('SessionGroup', 'Session Group'), ('Question', 'Question'), ('Agency', 'Agency'), ('Venue', 'Venue'), ('QualificationProgress', 'Qualification Progress'), ('QualificationAchievement', 'Qualification Achievement'), ('AddressBook', 'Address Book'), ('Report', 'Report')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='valuelistitem',
            name='valueList',
            field=models.ForeignKey(db_column='ValueListID', on_delete=django.db.models.deletion.CASCADE, to='admin_valuelists.valuelist'),
        ),
        migrations.AlterUniqueTogether(
            name='valuelist',
            unique_together={('Type', 'Name')},
        ),
    ]
