# Generated by Django 4.1.3 on 2023-03-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_valuelists', '0003_alter_valuelist_type_alter_valuelistitem_valuelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuelist',
            name='Type',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Volunteer', 'Volunteer'), ('Individual', 'Individual'), ('Person', 'Person'), ('Group', 'Group'), ('Session', 'Session'), ('SessionGroup', 'Session Group'), ('Question', 'Question'), ('Agency', 'Agency'), ('Venue', 'Venue'), ('QualificationProgress', 'Qualification Progress'), ('QualificationAchievement', 'Qualification Achievement'), ('AddressBook', 'Address Book'), ('Report', 'Report')], default='Staff', max_length=50),
        ),
    ]
