# Generated by Django 4.1.3 on 2023-04-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_valuelists', '0007_alter_valuelist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuelist',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='valuelist',
            name='Type',
            field=models.CharField(choices=[('staff', 'Staff'), ('volunteer', 'Volunteer'), ('individual', 'Individual'), ('person', 'Person'), ('group', 'Group'), ('session', 'Session'), ('sessiongroup', 'Session Group'), ('question', 'Question'), ('agency', 'Agency'), ('venue', 'Venue'), ('qualificationprogress', 'Qualification Progress'), ('qualificationachievement', 'Qualification Achievement'), ('addressbook', 'Address Book'), ('report', 'Report')], default='staff', max_length=50),
        ),
    ]
