# Generated by Django 4.1.3 on 2023-04-06 06:34

import admin_valuelists.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_valuelists', '0008_alter_valuelist_name_alter_valuelist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuelist',
            name='Name',
            field=admin_valuelists.models.LowerCaseCharField(max_length=50),
        ),
    ]
