# Generated by Django 4.1.3 on 2023-03-17 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('PersonID', models.AutoField(primary_key=True, serialize=False)),
                ('TypeName', models.CharField(choices=[('volunteer', 'Volunteer'), ('participant', 'Participant'), ('staff', 'Staff')], default=None, max_length=20, null=True)),
                ('Forename', models.CharField(max_length=30)),
                ('Surname', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('DateOfBirth', models.DateField()),
                ('Country', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Whatisyourfirstlanguage_V_19', models.CharField(max_length=20)),
                ('Ethnicity_V_15', models.CharField(max_length=20)),
                ('person', models.OneToOneField(db_column='PersonID', on_delete=django.db.models.deletion.CASCADE, related_name='volunteer', to='contacts.person')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstLanguage_P_88', models.CharField(max_length=20)),
                ('Ethnicity', models.CharField(max_length=20)),
                ('person', models.OneToOneField(db_column='PersonID', on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='contacts.person')),
            ],
        ),
    ]
