# Generated by Django 4.1.3 on 2023-03-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Volunteers',
            new_name='Volunteer',
        ),
    ]
