# Generated by Django 4.1.3 on 2023-04-03 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('AssociationID', models.AutoField(primary_key=True, serialize=False)),
                ('MasterType', models.CharField(choices=[('volunteer', 'Volunteer'), ('participant', 'Participant'), ('staff', 'Staff')], default=None, max_length=20, null=True)),
                ('SlaveType', models.CharField(choices=[('volunteer', 'Volunteer'), ('participant', 'Participant'), ('staff', 'Staff')], default=None, max_length=20, null=True)),
                ('Association', models.CharField(max_length=20)),
                ('Description', models.TextField()),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('MasterID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_association', to='contacts.participant')),
                ('SlaveID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slave_association', to='contacts.volunteer')),
            ],
        ),
    ]
