# Generated by Django 4.1.3 on 2023-04-07 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('views_sessions', '0002_alter_session_sessiongroupid_and_more'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('NoteID', models.AutoField(primary_key=True, serialize=False)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('CreatedBy', models.CharField(max_length=50)),
                ('UpdatedBy', models.CharField(max_length=50)),
                ('Note', models.CharField(max_length=500)),
                ('Private', models.IntegerField(choices=[(0, 'Public'), (1, 'Private')])),
                ('Type', models.CharField(choices=[('Person', 'Person'), ('Session', 'Session')], default='Person', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeID', models.ForeignKey(db_column='SessionID', on_delete=django.db.models.deletion.CASCADE, to='views_sessions.session')),
                ('note', models.OneToOneField(db_column='NoteID', on_delete=django.db.models.deletion.CASCADE, related_name='sessionNote', to='contacts.note')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeID', models.ForeignKey(db_column='PersonID', on_delete=django.db.models.deletion.CASCADE, to='contacts.person')),
                ('note', models.OneToOneField(db_column='NoteID', on_delete=django.db.models.deletion.CASCADE, related_name='participantNote', to='contacts.note')),
            ],
        ),
    ]
