# Generated by Django 4.1.3 on 2023-04-08 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_association'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='MasterID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_association', to='contacts.person'),
        ),
        migrations.AlterField(
            model_name='association',
            name='SlaveID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slave_association', to='contacts.person'),
        ),
    ]
