# Generated by Django 4.1.3 on 2023-04-09 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_association_masterid_alter_association_slaveid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='MasterID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_association', to='contacts.person'),
        ),
        migrations.AlterField(
            model_name='association',
            name='SlaveID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slave_association', to='contacts.person'),
        ),
    ]
