# Generated by Django 4.1.3 on 2023-04-07 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_delete_sessionnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeID', models.ForeignKey(db_column='PersonID', on_delete=django.db.models.deletion.CASCADE, to='contacts.person')),
                ('note', models.OneToOneField(db_column='NoteID', on_delete=django.db.models.deletion.CASCADE, related_name='personNote', to='contacts.note')),
            ],
        ),
        migrations.DeleteModel(
            name='ParticipantNote',
        ),
    ]
