# Generated by Django 4.1.3 on 2023-04-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_association_masterid_alter_association_slaveid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='association',
            constraint=models.CheckConstraint(check=models.Q(('MasterID', models.F('SlaveID')), _negated=True), name='master_slave_not_equal'),
        ),
    ]
