# Generated by Django 4.1.3 on 2023-04-09 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_association_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='MasterID',
            field=models.ForeignKey(db_column='MasterID', on_delete=django.db.models.deletion.CASCADE, related_name='master_association', to='contacts.person'),
        ),
        migrations.AlterField(
            model_name='association',
            name='SlaveID',
            field=models.ForeignKey(db_column='SlaveID', on_delete=django.db.models.deletion.CASCADE, related_name='slave_association', to='contacts.person'),
        ),
    ]
