# Generated by Django 4.1.3 on 2023-04-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_association_masterid_alter_association_slaveid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Country',
        ),
        migrations.AddField(
            model_name='participant',
            name='Countryofbirth_P_87',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='County',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
