# Generated by Django 4.1.3 on 2023-04-18 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_personnote_delete_participantnote'),
        ('contacts', '0008_remove_person_country_and_more'),
    ]

    operations = [
    ]
