# Generated by Django 3.2.7 on 2021-10-30 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentor_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorsession',
            name='user',
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='mentee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mentee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mentor', to=settings.AUTH_USER_MODEL),
        ),
    ]
