# Generated by Django 3.2.7 on 2021-11-23 01:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_sessions', '0002_auto_20211030_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorsession',
            name='attended_by_mentee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='attended_by_mentor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentorsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
