# Generated by Django 3.2.11 on 2022-04-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_sessions', '0004_auto_20211127_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyExpectedSessionCounts',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('january_count', models.IntegerField(default=0)),
                ('february_count', models.IntegerField(default=0)),
                ('march_count', models.IntegerField(default=0)),
                ('april_count', models.IntegerField(default=0)),
                ('may_count', models.IntegerField(default=0)),
                ('june_count', models.IntegerField(default=0)),
                ('july_count', models.IntegerField(default=0)),
                ('august_count', models.IntegerField(default=0)),
                ('september_count', models.IntegerField(default=0)),
                ('october_count', models.IntegerField(default=0)),
                ('november_count', models.IntegerField(default=0)),
                ('december_count', models.IntegerField(default=0)),
            ],
        ),
    ]
