# Generated by Django 3.2.11 on 2022-04-04 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_sessions', '0004_auto_20211127_0137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentorSession',
        ),
    ]
