# Generated by Django 3.2.11 on 2022-05-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentor_sessions', '0005_delete_mentorsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Youth mentoring', 'Youth mentoring'), ("Women's support", "Women's support"), ('Into School mentoring', 'Into School mentoring')], default='Youth mentoring', max_length=50)),
            ],
        ),
    ]
