# Generated by Django 3.2.11 on 2022-05-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_sessions', '0006_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
