# Generated by Django 3.2.11 on 2022-04-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_sessions', '0006_delete_monthlyexpectedsessioncounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorsession',
            name='wasCancelled',
            field=models.BooleanField(default=False),
        ),
    ]
