# Generated by Django 3.2.11 on 2022-05-30 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_sessions', '0006_mentorsession'),
        ('mentor_sessions', '0007_alter_activity_name'),
    ]

    operations = [
    ]
