# Generated by Django 3.2.11 on 2022-04-15 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_sessions', '0007_mentorsession_wascancelled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorsession',
            old_name='wasCancelled',
            new_name='cancelled',
        ),
    ]
