# Generated by Django 3.2.11 on 2022-04-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_sessions', '0008_rename_wascancelled_mentorsession_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorsession',
            name='viewsSessionId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
