# Generated by Django 3.2.11 on 2022-04-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_sessions', '0009_mentorsession_viewssessionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorsession',
            name='cancelled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
