# Generated by Django 3.2.14 on 2022-08-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0004_rename_holiday_calendarevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UkHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField()),
            ],
        ),
    ]
