# Generated by Django 3.2.7 on 2021-11-28 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions_and_answers', '__first__'),
        ('questionnaires', '0004_alter_monthlyreport_question_and_response_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='question_and_answer_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QARs_in_monthly_report', to='questions_and_answers.questionandanswer'),
        ),
        migrations.DeleteModel(
            name='QuestionAndResponse',
        ),
    ]
