# Generated by Django 3.2.7 on 2021-12-02 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaires', '0007_remove_monthlyreport_question_and_answer_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='mentee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questionnaire_mentee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questionnaire_mentor', to=settings.AUTH_USER_MODEL),
        ),
    ]
