# Generated by Django 3.2.7 on 2021-12-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor_stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorstats',
            name='sessions_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mentorstats',
            name='sessions_missed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mentorstats',
            name='sessions_total',
            field=models.IntegerField(default=0),
        ),
    ]
