# Generated by Django 3.2.11 on 2022-02-27 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=100)),
                ('period_in_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('is_read', models.BooleanField()),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notfication_mentor', to=settings.AUTH_USER_MODEL)),
                ('notification_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_notification_type', to='notifications.notificationtype')),
            ],
        ),
    ]
