# Generated by Django 3.2.11 on 2022-03-21 07:22

from django.db import migrations

def add_notification_types(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    NotificationType = apps.get_model('notifications', 'NotificationType')
    weekly_missing_questionnaire_reminder = NotificationType(
        title="Mentee's Questionnaire Missing", 
        content="Please complete the monthly questionnaire for {0} for mentee {1}.", 
        type="MISSING_QUESTIONNARIE_WEEKLY_REMINDER",
        period_in_days=30)
    weekly_missing_questionnaire_reminder.save()

class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_content'),
    ]

    operations = [
        migrations.RunPython(add_notification_types),
    ]
