from django.db import models

class SessionGroup(models.Model):
    SessionGroupID = models.PositiveIntegerField(primary_key=True)
    Title = models.CharField(max_length=255, null=True)
    Created = models.CharField(max_length=255, null=True)
    CreatedBy = models.CharField(max_length=255, null=True)
    Updated = models.CharField(max_length=255, null=True)
    UpdatedBy = models.CharField(max_length=255, null=True)
    Archived = models.CharField(max_length=255, null=True)
    ArchivedBy = models.CharField(max_length=255, null=True)
    RestrictedRecord = models.PositiveIntegerField(null=True)
    Type = models.CharField(max_length=255, null=True)
    Projects = models.PositiveIntegerField(null=True)
    BookingMode = models.CharField(max_length=255, null=True)
    AllowSessionTypes = models.CharField(max_length=255, null=True)
    Description = models.TextField(blank=True)
    LeadStaff = models.PositiveIntegerField(null=True)
    VenueID = models.PositiveIntegerField()
    StartDate = models.DateTimeField(null=True)
    EndDate = models.DateTimeField(null=True)
    PlannedSessions = models.PositiveIntegerField(null=True)
    AgeGroupFrom = models.PositiveIntegerField(null=True)
    AgeGroupTo = models.PositiveIntegerField(null=True)
    NumberOfPlaces = models.PositiveIntegerField(null=True)
