# Generated by Django 3.2.7 on 2021-10-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_admin_mentormore'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentormore',
            name='extra',
            field=models.CharField(default='', max_length=255),
        ),
    ]
