# Generated by Django 3.2.11 on 2022-02-14 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220206_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menteeuser',
            name='mentorid',
        ),
        migrations.AlterField(
            model_name='mentoruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mentoruser', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Mentoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menteeUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.menteeuser')),
                ('mentorUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.mentoruser')),
            ],
        ),
        migrations.AddField(
            model_name='mentoruser',
            name='menteeUsers',
            field=models.ManyToManyField(through='users.Mentoring', to='users.MenteeUser'),
        ),
    ]
