# Generated by Django 3.2.11 on 2022-03-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_menteeuser_mentorusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCreationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountType', models.CharField(choices=[('Mentor', 'Mentor'), ('Mentee', 'Mentee'), ('Admin', 'Admin')], default='Mentor', max_length=30)),
                ('viewsPersonId', models.CharField(default=None, max_length=30)),
                ('linkId', models.CharField(max_length=30)),
            ],
        ),
    ]
