# Generated by Django 3.2.11 on 2022-03-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_accountcreationlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountcreationlink',
            old_name='date',
            new_name='link_expiry_date',
        ),
    ]
