# Generated by Django 3.2.11 on 2022-03-30 02:53

from django.db import migrations, models
import users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_date_accountcreationlink_link_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('account_type', models.CharField(choices=[('Mentor', 'Mentor'), ('Mentee', 'Mentee'), ('Admin', 'Admin')], default='Mentor', max_length=30)),
                ('link_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('link_expiry_date', models.DateTimeField(blank=True, default=users.models.generateResetPasswordLinkExpiryDateTime)),
            ],
        ),
    ]
