# Generated by Django 3.2.11 on 2022-03-20 02:27

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20220318_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcreationlink',
            name='date',
            field=models.DateTimeField(blank=True, default=users.models.generateAccountCreationLinkExpiryDateTime),
        ),
        migrations.AddField(
            model_name='accountcreationlink',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
