# Generated by Django 3.2.11 on 2022-05-29 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_mentoruser_dataprivacyconsent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentoruser',
            name='dataPrivacyConsent',
        ),
        migrations.AddField(
            model_name='customuser',
            name='dataPrivacyConsent',
            field=models.DateField(default=None),
        ),
    ]
