# Generated by Django 3.2.11 on 2022-05-29 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20220528_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dataPrivacyConsent',
        ),
    ]
