# Generated by Django 3.2.11 on 2022-05-22 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mentor_sessions", "0007_alter_activity_name"),
        ("users", "0024_alter_mentorrole_viewssessiongroupid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mentorrole",
            name="activity",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mentor_sessions.activity",
            ),
        ),
    ]
