# Generated by Django 3.2.11 on 2022-05-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_customuser_data_privacy_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data_privacy_consent',
            field=models.DateField(null=True),
        ),
    ]
