# Generated by Django 3.2.11 on 2022-05-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_mentorrole_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorrole',
            name='activity',
            field=models.CharField(default='', max_length=150),
        ),
    ]
