# Generated by Django 3.2.11 on 2022-05-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_mentorrole_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorrole',
            name='viewsQuestionnaireId',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mentorrole',
            name='viewsSessionGroupId',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
