# Generated by Django 3.2.11 on 2022-05-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20220530_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorrole',
            name='viewsQuestionnaireId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mentorrole',
            name='viewsSessionGroupId',
            field=models.IntegerField(null=True),
        ),
    ]
