# Generated by Django 3.2.11 on 2022-05-30 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20220530_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoruser',
            name='mentorRole',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.mentorrole'),
        ),
    ]
