# Generated by Django 3.2.11 on 2022-06-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_mentoruser_mentorrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorrole',
            name='volunteeringType',
            field=models.CharField(default='', max_length=150),
        ),
    ]
