# Generated by Django 3.2.14 on 2022-11-12 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20220627_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_attended', models.PositiveIntegerField(default=0)),
                ('sessions_missed', models.PositiveIntegerField(default=0)),
                ('sessions_remaining', models.PositiveIntegerField(default=0)),
                ('sessions_total', models.PositiveIntegerField(default=0)),
                ('mentor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.mentoruser')),
            ],
        ),
    ]
