# Generated by Django 4.1.3 on 2023-03-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('SessionID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('SessionGroupID', models.PositiveIntegerField(null=True)),
                ('Created', models.DateTimeField(null=True)),
                ('CreatedBy', models.CharField(default='', max_length=255, null=True)),
                ('Updated', models.DateTimeField(null=True)),
                ('UpdatedBy', models.CharField(default='', max_length=255, null=True)),
                ('RestrictedRecord', models.PositiveIntegerField(null=True)),
                ('SessionType', models.CharField(default='', max_length=255, null=True)),
                ('Name', models.CharField(default='', max_length=255, null=True)),
                ('Activity', models.CharField(default='', max_length=255, null=True)),
                ('LeadStaff', models.PositiveIntegerField()),
                ('ContactType', models.CharField(default='', max_length=255, null=True)),
                ('StartDate', models.DateField(null=True)),
                ('StartTime', models.TimeField(null=True)),
                ('Duration', models.CharField(default='', max_length=255, null=True)),
                ('Cancelled', models.PositiveSmallIntegerField(null=True)),
                ('VenueID', models.PositiveIntegerField(null=True)),
                ('VenueName', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SessionID', models.PositiveIntegerField()),
                ('ContactType', models.CharField(max_length=255, null=True)),
                ('ContactID', models.PositiveIntegerField(null=True)),
                ('Attended', models.PositiveSmallIntegerField(null=True)),
                ('Role', models.CharField(max_length=255)),
                ('ReasonforNotAttending', models.TextField(null=True)),
                ('Name', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
