# Generated by Django 4.1.3 on 2023-03-20 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('views_api', '0002_sessiongroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessiongroup',
            old_name='AgeGroupFrom',
            new_name='OtherStaff',
        ),
        migrations.RemoveField(
            model_name='session',
            name='ContactType',
        ),
        migrations.RemoveField(
            model_name='session',
            name='CreatedBy',
        ),
        migrations.RemoveField(
            model_name='session',
            name='RestrictedRecord',
        ),
        migrations.RemoveField(
            model_name='session',
            name='SessionType',
        ),
        migrations.RemoveField(
            model_name='session',
            name='StartDate',
        ),
        migrations.RemoveField(
            model_name='session',
            name='StartTime',
        ),
        migrations.RemoveField(
            model_name='session',
            name='UpdatedBy',
        ),
        migrations.RemoveField(
            model_name='sessiongroup',
            name='AgeGroupTo',
        ),
        migrations.RemoveField(
            model_name='sessiongroup',
            name='AllowSessionTypes',
        ),
        migrations.RemoveField(
            model_name='sessiongroup',
            name='Archived',
        ),
        migrations.RemoveField(
            model_name='sessiongroup',
            name='ArchivedBy',
        ),
        migrations.RemoveField(
            model_name='sessiongroup',
            name='BookingMode',
        ),
        migrations.RemoveField(
            model_name='sessiongroup',
            name='Created',
        ),
        migrations.RemoveField(
            model_name='sessiongroup',
            name='CreatedBy',
        ),
        migrations.RemoveField(
            model_name='sessiongroup',
            name='EndDate',
        ),
        migrations.RemoveField(
            model_name='sessiongroup',
            name='NumberOfPlaces',
        ),
        migrations.RemoveField(
            model_name='sessiongroup',
            name='PlannedSessions',
        ),
        migrations.RemoveField(
            model_name='sessiongroup',
            name='Projects',
        ),
        migrations.RemoveField(
            model_name='sessiongroup',
            name='RestrictedRecord',
        ),
        migrations.RemoveField(
            model_name='sessiongroup',
            name='StartDate',
        ),
        migrations.RemoveField(
            model_name='sessiongroup',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='sessiongroup',
            name='Updated',
        ),
        migrations.RemoveField(
            model_name='sessiongroup',
            name='UpdatedBy',
        ),
        migrations.RemoveField(
            model_name='sessiongroup',
            name='VenueID',
        ),
        migrations.AlterField(
            model_name='session',
            name='SessionGroupID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='views_api.sessiongroup'),
        ),
        migrations.AlterField(
            model_name='sessiongroup',
            name='LeadStaff',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sessiongroup',
            name='Title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staffsession',
            name='SessionID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='views_api.session'),
        ),
    ]
