# Generated by Django 4.1.3 on 2023-03-22 21:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_volunteers_volunteer'),
        ('views_api', '0003_rename_agegroupfrom_sessiongroup_otherstaff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffsession',
            name='ContactType',
        ),
        migrations.AddField(
            model_name='session',
            name='StartDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='session',
            name='StartTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='session',
            name='Activity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='Cancelled',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='Duration',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='Name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='VenueID',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='VenueName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staffsession',
            name='ContactID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.person'),
        ),
    ]
