# Generated by Django 4.1.3 on 2023-03-22 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('views_api', '0004_remove_staffsession_contacttype_session_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='Created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
