# Generated by Django 4.1.3 on 2023-03-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views_api', '0005_alter_session_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffsession',
            name='Name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staffsession',
            name='ReasonforNotAttending',
            field=models.TextField(blank=True),
        ),
    ]
