# Generated by Django 4.1.3 on 2023-03-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views_api', '0006_alter_staffsession_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiongroup',
            name='LeadStaff',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
