# Generated by Django 4.1.3 on 2023-02-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeringtype',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
