# Generated by Django 4.1.3 on 2023-02-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering_types', '0002_volunteeringtype_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='volunteeringtype',
            table='views-mock-db',
        ),
    ]
